### ISSUE TITLE
Remove league/url dependency

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/url-signer#1]
The `league/url` package is deprecated in favor of `league/uri`. The latter requires php extensions to be installed which I'd rather avoid, so some refactoring would be required. Solutions: an alternative url package or a local implementation.

**Comment by danhunsaker** [comment]
Out of curiosity, why would `intl`, `mbstring`, and `fileinfo` be things to avoid?  As far as I'm aware, all three are generally installed by default.

**Comment by sebastiandedeyne** [comment]
At least one of them wasn't on Laravel Forge provisioned servers, so for us it was already a no go to require one.

I think they're available by default now though, but I'm not sure I'd want to do a major version bump for this dependency alone.

I'll give it some thought next week.
