### ISSUE TITLE
CloudFront UrlSigner

### ISSUE THREAD

**Issue by IlCallo** [spatie/url-signer#10]
Could you be interested into a UrlSigner based on the CloudFront PHP SDK?
I'll make one and I can do a PR if you like so.
I'd then make a PR also on the laravel-url-signer to allow the choice between the two UrlSigners

**Comment by sebastiandedeyne** [comment]
Since we have no need for signed CloudFront url's, we don't want to maintain this ourselves. Feel free to create your own signer that's compatible with this package. We can add a link to the readme's if you're interested :)

**Comment by IlCallo** [comment]
I ended up making my own package, based on yours, because some features (middleware, signature validation) weren't needed.
If you want to link it somewhere, it may be useful to do it from the `laravel-url-signer` package README instead of this one: in my case the "agnostic" version is the AWS SDK itself.

[laravel-cloudfront-url-signer](https://github.com/dreamonkey/laravel-cloudfront-url-signer)

**Comment by sebastiandedeyne** [comment]
Cool, added a little note to our readme :)
