### ISSUE TITLE
I don't think this is secure

### ISSUE THREAD

**Issue by josefsabl** [spatie/url-signer#20]
Please, guys, pull this goodie off of the github. It is horribly insecure.

1. Once your secret is leaked, you are pwned... If you think your secret will never leak then think again.

2. It is not very hard to reverse engineer the secret anyway.

I used to do the stuff like this as well, but always gave me creeps. At last I resorted to generating random tokens and storing them in database along with their expiration, it was not that hard.

**Comment by bdsl** [comment]
@josefsabl It's true that if the secret leaks this will stop providing any security. People normally handle that by rotating secrets.

I don't see any easy way to reverse engineer the secret, assuming its a long string of random characters. If you've found one it would be good if you can describe it, ideally first by getting touch with Spatie, or one of their developers who worked on this, and then here if you get no response from them.

**Comment by josefsabl** [comment]
> I don't see any easy way to reverse engineer the secret, assuming its a long string of random characters. If you've found one it would be good if you can describe it, ideally first by getting touch with Spatie, or one of their developers who worked on this, and then here if you get no response from them.

Well, I long deleted the script but as I remember the md5 (at least as default?) is used which is very fast/weak for cryptographic purpose. The brute force script with a reasonable secret (8 chars, a-z0-9) used took like a few seconds on my workstation. If you can imagine some computational farm or using rainbow tables...

I, of course, contacted Spatie via e-mail with much more detail as well as the snippet of the script and with no response. So I thought I would leave this message here for anyone who wanted to use this ... stuff.

Please don't, if you use this and someone wants to hack you, he will.

**Comment by josefsabl** [comment]
I found the script. It was a long time since I reported it so I guess the shame is on them if some kid gets hacked. I must stress I am no hacker or anything. Just a regular dev.

https://gist.github.com/josefsabl/8241f17a35ff506950f1ddf0e01f0850

**Comment by josefsabl** [comment]
> It's true that if the secret leaks this will stop providing any security. People normally handle that by rotating secrets.

To put it first. I stressed this obvious point as to make the post complete. I think the second point is much more important because you can get to the secret by reverse engineering anyways.

But, this argument is flawed as it is if you think about it. When do you change the secret? a) when the breach is discovered. b) randomly as a precaution.

a) So the breach was detected and the damage was done. And the attacker had at least some time to download all your secret data before you had a chance to change the secret.

b) There is no way to tell if anybody breached your security. It is very likely that the channel the attacker used to get the secret is still open and he will get the new secret as well. Also, there was at least some time between the breach and your random secret reset and all your secret data would be downloaded by the time you change the secret.

I understand there have to be secrets and they have to be guarded and they always are prone to getting leaked. But you also have other means to protect your data. E.g. you, of course, have a password for your database. But you also have access to the database protected by other means. It would be foolish to have PhpMyAdmin open to the world and pray that none of your developers would leak their personal password. You protect access to your database by VPN, IP whitelist, whatever. By using this ... library, you turn the very webapp to access point to your database.

**Comment by bdsl** [comment]
Your script shows that given the knowledge that the secret is an integer between 0 and 99999999 (eight digits) you can brute force it in 132 seconds. 

But the user could avoid that by choosing a better secret - if instead of an eight digit number they had a random 28 digit number then your script would expect to take over a hundred thousand years. If they randomly replaced some of the numbers with letters it would take many times more again.

I'm not recommending this - I agree that there are much better algorithms than MD5, and since various attacks against MD5 has been demonstrated it's no longer really recommended for any security critical use, but as far as I can see it isn't obviously crackable if used well.

**Comment by josefsabl** [comment]
> Your script shows that given the knowledge that the secret is an integer between 0 and 99999999 (eight digits) you can brute force it in 132 seconds.
> 
> But the user could avoid that by choosing a better secret - if instead of an eight digit number they had a random 28 digit number then your script would expect to take over a hundred thousand years. If they randomly replaced some of the numbers with letters it would take many times more again.
> 
> I'm not recommending this - I agree that there are much better algorithms than MD5, and since various attacks against MD5 has been demonstrated it's no longer really recommended for any security critical use, but as far as I can see it isn't obviously crackable if used well.

I strongly disagree. My script shows that it can be brute forced with no effort, no special knowledge and ridiculous hardware in a reasonable time when not a very strong (but not extremely weak either) secret is used.

It however doesn't disproof that it cannot be brute forced in reasonable time even for strong secrets with appropriate cryptographic know-how and appropriate hardware.

See [this article I just Googled](https://www.quora.com/Is-it-true-that-md5-isnt-safe-enough-for-web-applications). Excerpt: "So MD5 isn’t useless—it’s just that it shouldn’t be used as a secure hashing algorithm.".

Also, see [Wikipedia](https://en.wikipedia.org/wiki/MD5) Excerpt: "The MD5 message-digest algorithm is a widely used hash function producing a 128-bit hash value. Although MD5 was initially designed to be used as a cryptographic hash function, it has been found to suffer from extensive vulnerabilities."

And: [180 000 000 000 MD5 hashes per second](https://www.zdnet.com/article/25-gpus-devour-password-hashes-at-up-to-348-billion-per-second/)

Also:

Yes, I agree that if I used functionality like this in my application, I would choose my secret appropriately (also an appropriate hashing algorithm). 

But the nature of this rather simple library suggests it is targeted on, well, wide 'clueless' audience (and I by no means mean the word clueless pejoratively), who will copy paste the snippets, maybe changing the secrets a bit.

It also doesn't check the secret strength, doesn't state anything about the security concerns of weak secrets and the examples use ridiculous secrets themselves.

And there also prevails the problem with the leaked secret.

I was jokingly thinking this might be successfully deployed as a Trojan the authors would use to hack other peoples webpages. Just think about it ;-)

**Comment by paxperscientiam** [comment]
This isn't encryption, so you shouldn't be using it to hide secrets on the Internet. It's useful for making fuzzing more difficult, which is what I use it for.
