### ISSUE TITLE
Validation fails if query params include urlencodable characters

### ISSUE THREAD

**Issue by Tib-z** [spatie/url-signer#56]
Hi,
I just upgraded the package and noticed IMHO a major bug. If the url contains query params which are url encodable, the validation will fail, because when the signature is created it uses the url "as is". 
https://github.com/spatie/url-signer/blob/49e8b4fc48ed2a12b0f612e24a8ba24c759d8a2f/src/AbstractUrlSigner.php#L39
But the returned signed url already has modified query params, since in the Url::addQueryParameters http_build_query() call automatically url encodes the parameters.
https://github.com/spatie/url-signer/blob/49e8b4fc48ed2a12b0f612e24a8ba24c759d8a2f/src/Support/Url.php#L24

Basically the same happens at validation, the passed url is always parsed and urlencoded by the AbstractUrlSigner::getIntendedUrl() call, so even though the correct url is passed (which was used to calculate the signature) the intended url's signature will not match the initially calculated signature.

I guess the easiest solution would be to also parse the url before signing, e.g. calling getIntendedUrl. It might seem hackish, but it is actually required, since the original "intended" url must not have expires and signature params, and to ensure the url format consistency.

```
public function sign(
        string $url,
        int|DateTimeInterface $expiration,
        string $signatureKey = null,
    ): string {
        $signatureKey ??= $this->defaultSignatureKey;

        $expiration = $this->getExpirationTimestamp($expiration);

++        $url = $this->getIntendedUrl($url);
        
        $signature = $this->createSignature($url, $expiration, $signatureKey);

        return $this->signUrl($url, $expiration, $signature);
    }
```

**Comment by freekmurze** [comment]
Could you PR a test that fails with the current code? Feel free to also include the fix in the PR.

**Comment by Tib-z** [comment]
Sure, I'll do it this week.
