### ISSUE TITLE
league/url package is abandoned and no longer maintained

### ISSUE THREAD

**Issue by meness** [spatie/url-signer#6]
Hi,

The author suggests using the [league/uri](https://packagist.org/packages/league/uri) package instead.

**Comment by sebastiandedeyne** [comment]
See #1 :)

**Comment by siarheipashkevich** [comment]
@sebastiandedeyne could you please tell me how to fix this problem?

**Comment by sebastiandedeyne** [comment]
You can't, unless you fork this package and replace the dependency with `league/uri`.

Note that this isn't really a problem, it's just a warning, everything still works as intended.

**Comment by siarheipashkevich** [comment]
I agree that's just warning, but why the creator can't replace this package?

**Comment by sebastiandedeyne** [comment]
See #1, because the alternative package requires non-default PHP extensions. We'll probably revisit this in the future, but it's low on our priority list.

**Comment by siarheipashkevich** [comment]
@sebastiandedeyne got it. Thank you so much.
