### ISSUE TITLE
Always needed to be instantiated?

### ISSUE THREAD

**Issue by codetensor** [spatie/url-signer#9]
Hi I just recently used this library, but I want to ask something, is it always needed to be instantiated or created new object just to use this?

What if we want to use the Signer in code A, and the validate in code B, repeat the code all the way? 

And I have checked the Laravel URL Signer which have :: or static access object. why don't this URL-Signer has the same? 

Thank You

**Comment by sebastiandedeyne** [comment]
We don't really provide static access in the Laravel package, it provides a [Laravel facade](https://laravel.com/docs/5.5/facades).

Are you using a framework? Generally I'd recommend binding an instance of the url-signer to your service container, which is exactly what happens in the Laravel package.

**Comment by codetensor** [comment]
Hi Sebastian, 

Yes but umm, I am using Laravel Eloquent for my ORM, Twig for template engine, let say Hybrid. 

I am thinking that this can be used for resetting password link, activating user account with the limited time access

**Comment by sebastiandedeyne** [comment]
If you're not using a framework, I can't make any recommendations on where you should store the url signer instance.

It doesn't really matter if you instantiate it multiple times though, besides the repetition in your code. If you want to store a singleton of the url signer, consider writing your own wrapper class or use a service container.
